name: Keep Alive

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: |
          curl -L \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/122.0.0.0" \
          https://jobmarketpulse.streamlit.app
